### ISSUE TITLE
tzdata depencency version

### ISSUE THREAD

**Issue by BrunoMiglioretto** [ForestAdmin/agent-python#190]
Hi.

I'm having a dependency resolution error with `tzdata` packege when installing Celery 5.3.6 with forestadmin-agent-toolkit 1.5.3. While Celery need tzdata with version `2022.7` or above, forestadmin-agent-toolkit need `tzdata` in version `2022.6`.

![image](https://github.com/ForestAdmin/agent-python/assets/42503533/1b696f55-6975-4ff6-9c7f-d1945b63ab31)

Is it possible to make forestadmin-agent-toolkit package work with `tzdata` in version `2022.7` or above?

**Comment by jbarreau** [comment]
Hi @BrunoMiglioretto,
I just open a pull request for this, it should be merged soon.

**Comment by jbarreau** [comment]
It's now release on pypi (1.5.4).

**Comment by BrunoMiglioretto** [comment]
I appreciate it!
